$schema: http://json-schema.org/draft-04/schema#
type: object
properties:
  date:
    $ref: ../../00-atoms/components/date.yaml
  statusText:
    type: string
    minLength: 1
  statusDate:
    $ref: ../../00-atoms/components/date.yaml
anyOf:
  -
    required:
      - date
